export const userDebtPositions = [
    {
      debtAsset: "0x1234...EURC",
      symbol: "EURC",
      name: "Euro Coin",
      icon: "🇪🇺",
      supplyBalance: "2500.00",
      borrowBalance: "1800.00",
      balanceUSD: "1980.00",
      ltv: "72.0",
      liqLTV: "85.0",
      penalty: "5.0",
      netBorrow: "700.00",
      interestRate: "0.0",
    },
    {
      debtAsset: "0x5678...USDC",
      symbol: "USDC",
      name: "USD Coin",
      icon: "💵",
      supplyBalance: "1200.00",
      borrowBalance: "800.00",
      balanceUSD: "800.00",
      ltv: "66.7",
      liqLTV: "80.0",
      penalty: "10.0",
      netBorrow: "400.00",
      interestRate: "0.0",
    },
  ]

  // Mock user collateral positions data
  export const userCollateralPositions = [
    {
      collateralAsset: "0xdef0...ETH",
      symbol: "ETH",
      name: "Ethereum",
      icon: "🔷",
      supplyBalance: "1.25",
      balanceUSD: "4275.00",
      netBase: "0.85",
      baseRate: "2.1",
      currentRate: "4.2",
      utilizationRate: "75.5",
    },
    {
      collateralAsset: "0x1111...stETH",
      symbol: "stETH",
      name: "Staked Ethereum",
      icon: "🟣",
      supplyBalance: "0.75",
      balanceUSD: "2561.25",
      netBase: "0.65",
      baseRate: "3.2",
      currentRate: "5.8",
      utilizationRate: "68.2",
    },
  ]

  // Mock asset data based on AssetData structure
  export const debtAssets = [
    {
      asset: "0x1234...EURC",
      symbol: "EURC",
      name: "Euro Coin",
      icon: "🇪🇺",
      decimals: 6,
      supplyCap: "10000000",
      borrowCap: "8000000",
      totalSupply: "2400000",
      totalBorrow: "1800000",
      utilizationRate: "750000000000000000", // 75% in 1e18
      supplyRate: "450", // 4.5% APR in bps
      borrowRate: "0", // 0% for zero-interest
      isFrozen: false,
      isPaused: false,
      color: "#8b5cf6",
      protocols: ["Morpho", "Aave"],
    },
    {
      asset: "0x5678...EURI",
      symbol: "EURI",
      name: "Euro Stablecoin",
      icon: "💶",
      decimals: 18,
      supplyCap: "5000000",
      borrowCap: "4000000",
      totalSupply: "1200000",
      totalBorrow: "900000",
      utilizationRate: "750000000000000000",
      supplyRate: "380",
      borrowRate: "0",
      isFrozen: false,
      isPaused: false,
      color: "#06b6d4",
      protocols: ["Compound", "Morpho"],
    },
    {
      asset: "0x9abc...USDC",
      symbol: "USDC",
      name: "USD Coin",
      icon: "💵",
      decimals: 6,
      supplyCap: "15000000",
      borrowCap: "12000000",
      totalSupply: "8500000",
      totalBorrow: "6200000",
      utilizationRate: "729411764705882353",
      supplyRate: "520",
      borrowRate: "0",
      isFrozen: false,
      isPaused: false,
      color: "#2775CA",
      protocols: ["Aave", "Compound"],
    },
  ]

  export const collateralAssets = [
    {
      asset: "0xdef0...ETH",
      symbol: "ETH",
      name: "Ethereum",
      icon: "🔷",
      decimals: 18,
      supplyCap: "50000",
      borrowCap: "40000",
      totalSupply: "12500",
      ltv: "7500", // 75% in bps
      liquidationThreshold: "8000", // 80% in bps
      liquidationBonus: "500", // 5% in bps
      reserveFactor: "1000", // 10% in bps
      isFrozen: false,
      isPaused: false,
      color: "#627EEA",
      currentPrice: 3420,
      apy: "4.2%",
      stakedTokens: [
        { protocol: "Lido", amount: "8500", apy: "3.8%" },
        { protocol: "RocketPool", amount: "4000", apy: "4.1%" },
      ],
    },
    {
      asset: "0x1111...stETH",
      symbol: "stETH",
      name: "Staked Ethereum",
      icon: "🟣",
      decimals: 18,
      supplyCap: "30000",
      borrowCap: "24000",
      totalSupply: "8200",
      ltv: "7000",
      liquidationThreshold: "7500",
      liquidationBonus: "750",
      reserveFactor: "1000",
      isFrozen: false,
      isPaused: false,
      color: "#00A3FF",
      currentPrice: 3415,
      apy: "5.8%",
      stakedTokens: [{ protocol: "Lido", amount: "8200", apy: "5.8%" }],
    },
    {
      asset: "0x2222...WBTC",
      symbol: "WBTC",
      name: "Wrapped Bitcoin",
      icon: "🟠",
      decimals: 8,
      supplyCap: "1000",
      borrowCap: "700",
      totalSupply: "245",
      ltv: "7000",
      liquidationThreshold: "7500",
      liquidationBonus: "1000",
      reserveFactor: "1500",
      isFrozen: false,
      isPaused: false,
      color: "#F7931A",
      currentPrice: 67800,
      apy: "2.9%",
      stakedTokens: [],
    },
    {
      asset: "0x3333...LINK",
      symbol: "LINK",
      name: "Chainlink",
      icon: "🔗",
      decimals: 18,
      supplyCap: "500000",
      borrowCap: "350000",
      totalSupply: "125000",
      ltv: "6500",
      liquidationThreshold: "7000",
      liquidationBonus: "1000",
      reserveFactor: "2000",
      isFrozen: false,
      isPaused: false,
      color: "#375BD2",
      currentPrice: 14.5,
      apy: "3.1%",
      stakedTokens: [],
    },
  ]

  export const vaultStrategies = [
    {
      name: "ETH Liquid Staking",
      risk: "Low",
      apy: "6.2%",
      color: "from-green-500 to-green-400",
      recommended: true,
      description: "Stake your ETH and earn yield through liquid staking protocols.",
      protocols: ["Lido", "RocketPool"],
    },
    {
      name: "Stablecoin Lending",
      risk: "Low",
      apy: "4.8%",
      color: "from-blue-500 to-blue-400",
      recommended: false,
      description: "Lend stablecoins and earn interest with minimal risk.",
      protocols: ["Aave", "Compound"],
    },
    {
      name: "DeFi Blue-Chip Vault",
      risk: "Medium",
      apy: "8.7%",
      color: "from-purple-500 to-purple-400",
      recommended: false,
      description: "Earn yield on a basket of blue-chip DeFi tokens.",
      protocols: ["Aave", "Yearn", "Curve"],
    },
  ]

  export const borrowAssets = [
    {
      asset: "0x1234...EURC",
      symbol: "EURC",
      name: "Euro Coin",
      icon: "🇪🇺",
      decimals: 6,
      rate: "0%",
    },
    {
      asset: "0x5678...USDC",
      symbol: "USDC",
      name: "USD Coin",
      icon: "💵",
      decimals: 6,
      rate: "0%",
    },
    {
      asset: "0x9abc...DAI",
      symbol: "DAI",
      name: "Dai Stablecoin",
      icon: "♦️",
      decimals: 18,
      rate: "0%",
    },
  ]


export const ASSET_METADATA: Record<string, { symbol: string; name: string; icon: string; color: string; protocols: string[] }> = {
  // Add your asset metadata here based on contract addresses
  "0x8Cd770860726aab1151D6d9D7F05Fab9D4C68Ef4": { symbol: 'EURC', name: 'Euro Coin', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/20641.png', color: '#8b5cf6', protocols: ['Morpho', 'Aave'] },
  '0x5678...EURI': { symbol: 'EURI', name: 'Euro Stablecoin', icon: '💶', color: '#06b6d4', protocols: ['Compound', 'Morpho'] },
  '0x9abc...USDC': { symbol: 'USDC', name: 'USD Coin', icon: '💵', color: '#2775CA', protocols: ['Aave', 'Compound'] },
  // Collateral Assets
    '0xdef0...ETH': { symbol: 'ETH', name: 'Ethereum', icon: '🔷', color: '#627EEA', protocols: ['Lido', 'RocketPool'] },
    '0x1111...stETH': { symbol: 'stETH', name: 'Staked Ethereum', icon: '🟣', color: '#00A3FF', protocols: ['Lido'] },
    '0x2222...WBTC': { symbol: 'WBTC', name: 'Wrapped Bitcoin', icon: '🟠', color: '#F7931A', protocols: [] },
  "0x779877A7B0D9E8603169DdbD7836e478b4624789": { symbol: 'LINK', name: 'Chainlink', icon: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1975.png', color: '#375BD2', protocols: [] },
}